### List all messages
GET  http://localhost:3000/messages


### create new message
Post http://localhost:3000/messages
Content-type: application/json

{"content":"third message"}


###
GET  http://localhost:3000/messages/166
